import{createClient}from'@supabase/supabase-js';import type{FlightStatus,Schedule,Settings}from'./types'
export const TZ='America/Sao_Paulo'
export const supabase=createClient(import.meta.env.VITE_SUPABASE_URL||'https://qjnaptukxhwffvacixdz.supabase.co',import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_yQ2kQRXiUZrbWbrKlU10aQ_8WJcI0b5',{auth:{persistSession:false}})
export const defaultSettings:Settings={id:'00000000-0000-0000-0000-000000000001',display_lead_minutes:120,checkin_minutes_before:30,boarding_minutes_before:10,last_call_minutes_before:3,gate_closed_minutes_after_start:5,retain_after_end_minutes:60,page_rotation_seconds:12}
export function zonedParts(date=new Date()){const ps=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23',weekday:'short'}).formatToParts(date),g=(t:string)=>ps.find(p=>p.type===t)?.value||'',weekday=({Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7}as Record<string,number>)[g('weekday')];return{date:`${g('year')}-${g('month')}-${g('day')}`,minutes:+g('hour')*60 + +g('minute'),weekday,time:`${g('hour')}:${g('minute')}`}}
const mins=(t:string)=>{const[h,m]=t.slice(0,5).split(':').map(Number);return h*60+m}
export function getAutomaticStatus(s:Pick<Schedule,'start_time'|'end_time'>,x:Settings,n:number):FlightStatus|null{const start=mins(s.start_time),end=mins(s.end_time),d=start-n;if(d>x.display_lead_minutes||n>end+x.retain_after_end_minutes)return null;if(d>x.checkin_minutes_before)return'on_time';if(d>x.boarding_minutes_before)return'check_in';if(d>x.last_call_minutes_before)return'boarding';if(d>0)return'last_call';if(n<=start+x.gate_closed_minutes_after_start)return'gate_closed';return'departed'}
export function effectiveStatus(s:Schedule,x:Settings,date:string,n:number){return s.manual_status&&s.manual_status_date===date?s.manual_status:getAutomaticStatus(s,x,n)}
export async function loadData(){const[rooms,teachers,schedules,settings]=await Promise.all([supabase.from('rooms').select('*').order('code'),supabase.from('teachers').select('*').order('name'),supabase.from('class_schedules').select('*').order('start_time'),supabase.from('app_settings').select('*').limit(1).maybeSingle()]);const error=rooms.error||teachers.error||schedules.error||settings.error;if(error)throw error;return{rooms:rooms.data||[],teachers:teachers.data||[],schedules:schedules.data||[],settings:settings.data||defaultSettings}}
export function invokeAdmin(password:string,action:string,payload:unknown={}){return supabase.functions.invoke('admin-api',{body:{action,payload},headers:{'x-admin-password':password}})}
